<?php
DEFINE("MANAGERPASS","649859");
DEFINE("BOTTOKEN","");
DEFINE("DBTYPE","mysql");
DEFINE("MYSQL_HOST","localhost");
DEFINE("MYSQL_USER","evkovalevg");
DEFINE("MYSQL_PASSWORD","telegram5421");
DEFINE("MYSQL_DBNAME","evkovalevg");
DEFINE("WEBHOOKSCRIPT","telegram-site-helper-get-webhook_57759ec08594e.php");
